apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: realestate

resources:
  - ../../base

patches:
  # Production replicas
  - target:
      kind: Deployment
      name: gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: auth-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: inventory-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: crm-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3

  # Override ConfigMap for prod
  - target:
      kind: ConfigMap
      name: app-config
    patch: |
      - op: replace
        path: /data/NODE_ENV
        value: "production"
      - op: add
        path: /data/LOG_LEVEL
        value: "warn"

  # Production resource bumps
  - target:
      kind: Deployment
      name: gateway
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

images:
  - name: realestate/gateway
    newName: acrrealestateshared.azurecr.io/realestate/gateway
    newTag: latest
  - name: realestate/auth-service
    newName: acrrealestateshared.azurecr.io/realestate/auth-service
    newTag: latest
  - name: realestate/inventory-service
    newName: acrrealestateshared.azurecr.io/realestate/inventory-service
    newTag: latest
  - name: realestate/supply-chain-service
    newName: acrrealestateshared.azurecr.io/realestate/supply-chain-service
    newTag: latest
  - name: realestate/crm-service
    newName: acrrealestateshared.azurecr.io/realestate/crm-service
    newTag: latest
  - name: realestate/notification-service
    newName: acrrealestateshared.azurecr.io/realestate/notification-service
    newTag: latest
  - name: realestate/document-service
    newName: acrrealestateshared.azurecr.io/realestate/document-service
    newTag: latest
  - name: realestate/web
    newName: acrrealestateshared.azurecr.io/realestate/web
    newTag: latest
